//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LookupRelatedDataManagementServiceSR
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetLookupRelationalRecordsRequest", Namespace="http://TETCO.SOA.Entity.MDM.DataContracts.Requests/LookupRelatedData/GetLookupRel" +
        "ationalRecordsRequest/V1.0")]
    public partial class GetLookupRelationalRecordsRequest : object
    {
        
        private string RelationContainerCodeField;
        
        private string MasterLookupCodeField;
        
        private string MasterRecordCodeField;
        
        private string ParentCodeField;
        
        private System.Collections.Generic.List<string> LanguageCodesField;
        
        private System.Collections.Generic.List<string> MetadataFieldCodesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RelationContainerCode
        {
            get
            {
                return this.RelationContainerCodeField;
            }
            set
            {
                this.RelationContainerCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string MasterLookupCode
        {
            get
            {
                return this.MasterLookupCodeField;
            }
            set
            {
                this.MasterLookupCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string MasterRecordCode
        {
            get
            {
                return this.MasterRecordCodeField;
            }
            set
            {
                this.MasterRecordCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string ParentCode
        {
            get
            {
                return this.ParentCodeField;
            }
            set
            {
                this.ParentCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public System.Collections.Generic.List<string> LanguageCodes
        {
            get
            {
                return this.LanguageCodesField;
            }
            set
            {
                this.LanguageCodesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public System.Collections.Generic.List<string> MetadataFieldCodes
        {
            get
            {
                return this.MetadataFieldCodesField;
            }
            set
            {
                this.MetadataFieldCodesField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseBase", Namespace="http://TETCO.SOA.Common.DataContracts.Responses/ResponseBase/V1.0")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LookupRelatedDataManagementServiceSR.DetachLookupRecordsResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LookupRelatedDataManagementServiceSR.AttachLookupRecordsResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LookupRelatedDataManagementServiceSR.GetLookupRelationalRecordsByMetadataResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LookupRelatedDataManagementServiceSR.GetLookupRelationalRecordsByBusinessCodeNoParentCodeResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LookupRelatedDataManagementServiceSR.GetLookupRelationalRecordsByBusinessCodeResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LookupRelatedDataManagementServiceSR.GetLookupRelationalRecordsByLookupNameAndBusinessCodeResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LookupRelatedDataManagementServiceSR.GetLookupRelationalRecordParentsResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LookupRelatedDataManagementServiceSR.GetLookupRelationalRecordsResponse))]
    public partial class ResponseBase : object
    {
        
        private LookupRelatedDataManagementServiceSR.OperationResult OperationResultField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LookupRelatedDataManagementServiceSR.OperationResult OperationResult
        {
            get
            {
                return this.OperationResultField;
            }
            set
            {
                this.OperationResultField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OperationResult", Namespace="http://TETCO.SOA.Common.DataContracts.OperationsResults/OperationResult/V1.0")]
    public partial class OperationResult : object
    {
        
        private LookupRelatedDataManagementServiceSR.Result ResultField;
        
        private string JustificationField;
        
        private LookupRelatedDataManagementServiceSR.ESBFault FaultField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LookupRelatedDataManagementServiceSR.Result Result
        {
            get
            {
                return this.ResultField;
            }
            set
            {
                this.ResultField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string Justification
        {
            get
            {
                return this.JustificationField;
            }
            set
            {
                this.JustificationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public LookupRelatedDataManagementServiceSR.ESBFault Fault
        {
            get
            {
                return this.FaultField;
            }
            set
            {
                this.FaultField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DetachLookupRecordsResponse", Namespace="http://TETCO.SOA.Entity.MDM.DataContracts.Responses/LookupRelatedData/DetachLooku" +
        "pRecordsResponse/V1.0")]
    public partial class DetachLookupRecordsResponse : LookupRelatedDataManagementServiceSR.ResponseBase
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AttachLookupRecordsResponse", Namespace="http://TETCO.SOA.Entity.MDM.DataContracts.Responses/LookupRelatedData/AttachLooku" +
        "pRecordsResponse/V1.0")]
    public partial class AttachLookupRecordsResponse : LookupRelatedDataManagementServiceSR.ResponseBase
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetLookupRelationalRecordsByMetadataResponse", Namespace="http://TETCO.SOA.Entity.MDM.DataContracts.Responses/LookupRelatedData/GetLookupRe" +
        "lationalRecordsByMetadataResponse/V1.0")]
    public partial class GetLookupRelationalRecordsByMetadataResponse : LookupRelatedDataManagementServiceSR.ResponseBase
    {
        
        private LookupRelatedDataManagementServiceSR.LookupInfo MasterLookupField;
        
        private LookupRelatedDataManagementServiceSR.LookupInfo DetailLookupField;
        
        private LookupRelatedDataManagementServiceSR.LookupRecord MasterRecordField;
        
        private System.Collections.Generic.List<LookupRelatedDataManagementServiceSR.LookupRelationContainerDetailDataRecords> DetailRecordsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LookupRelatedDataManagementServiceSR.LookupInfo MasterLookup
        {
            get
            {
                return this.MasterLookupField;
            }
            set
            {
                this.MasterLookupField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public LookupRelatedDataManagementServiceSR.LookupInfo DetailLookup
        {
            get
            {
                return this.DetailLookupField;
            }
            set
            {
                this.DetailLookupField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public LookupRelatedDataManagementServiceSR.LookupRecord MasterRecord
        {
            get
            {
                return this.MasterRecordField;
            }
            set
            {
                this.MasterRecordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.Collections.Generic.List<LookupRelatedDataManagementServiceSR.LookupRelationContainerDetailDataRecords> DetailRecords
        {
            get
            {
                return this.DetailRecordsField;
            }
            set
            {
                this.DetailRecordsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetLookupRelationalRecordsByBusinessCodeNoParentCodeResponse", Namespace="http://TETCO.SOA.Entity.MDM.DataContracts.Responses/LookupRelatedData/GetLookupRe" +
        "lationalRecordsByBusinessCodeNoParentCodeResponse/V1.0")]
    public partial class GetLookupRelationalRecordsByBusinessCodeNoParentCodeResponse : LookupRelatedDataManagementServiceSR.ResponseBase
    {
        
        private LookupRelatedDataManagementServiceSR.LookupInfo MasterLookupField;
        
        private LookupRelatedDataManagementServiceSR.LookupInfo DetailLookupField;
        
        private LookupRelatedDataManagementServiceSR.LookupRecord MasterRecordField;
        
        private System.Collections.Generic.List<LookupRelatedDataManagementServiceSR.LookupRelationContainerDetailDataRecords> DetailRecordsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LookupRelatedDataManagementServiceSR.LookupInfo MasterLookup
        {
            get
            {
                return this.MasterLookupField;
            }
            set
            {
                this.MasterLookupField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public LookupRelatedDataManagementServiceSR.LookupInfo DetailLookup
        {
            get
            {
                return this.DetailLookupField;
            }
            set
            {
                this.DetailLookupField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public LookupRelatedDataManagementServiceSR.LookupRecord MasterRecord
        {
            get
            {
                return this.MasterRecordField;
            }
            set
            {
                this.MasterRecordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.Collections.Generic.List<LookupRelatedDataManagementServiceSR.LookupRelationContainerDetailDataRecords> DetailRecords
        {
            get
            {
                return this.DetailRecordsField;
            }
            set
            {
                this.DetailRecordsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetLookupRelationalRecordsByBusinessCodeResponse", Namespace="http://TETCO.SOA.Entity.MDM.DataContracts.Responses/LookupRelatedData/GetLookupRe" +
        "lationalRecordsByBusinessCodeResponse/V1.0")]
    public partial class GetLookupRelationalRecordsByBusinessCodeResponse : LookupRelatedDataManagementServiceSR.ResponseBase
    {
        
        private LookupRelatedDataManagementServiceSR.LookupInfo MasterLookupField;
        
        private LookupRelatedDataManagementServiceSR.LookupInfo DetailLookupField;
        
        private LookupRelatedDataManagementServiceSR.LookupRecord MasterRecordField;
        
        private System.Collections.Generic.List<LookupRelatedDataManagementServiceSR.LookupRelationContainerDetailDataRecords> DetailRecordsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LookupRelatedDataManagementServiceSR.LookupInfo MasterLookup
        {
            get
            {
                return this.MasterLookupField;
            }
            set
            {
                this.MasterLookupField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public LookupRelatedDataManagementServiceSR.LookupInfo DetailLookup
        {
            get
            {
                return this.DetailLookupField;
            }
            set
            {
                this.DetailLookupField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public LookupRelatedDataManagementServiceSR.LookupRecord MasterRecord
        {
            get
            {
                return this.MasterRecordField;
            }
            set
            {
                this.MasterRecordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.Collections.Generic.List<LookupRelatedDataManagementServiceSR.LookupRelationContainerDetailDataRecords> DetailRecords
        {
            get
            {
                return this.DetailRecordsField;
            }
            set
            {
                this.DetailRecordsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetLookupRelationalRecordsByLookupNameAndBusinessCodeResponse", Namespace="http://TETCO.SOA.Entity.MDM.DataContracts.Responses/LookupRelatedData/GetLookupRe" +
        "lationalRecordsByLookupNameAndBusinessCodeResponse/V1.0")]
    public partial class GetLookupRelationalRecordsByLookupNameAndBusinessCodeResponse : LookupRelatedDataManagementServiceSR.ResponseBase
    {
        
        private LookupRelatedDataManagementServiceSR.LookupInfo MasterLookupField;
        
        private LookupRelatedDataManagementServiceSR.LookupInfo DetailLookupField;
        
        private LookupRelatedDataManagementServiceSR.LookupRecord MasterRecordField;
        
        private System.Collections.Generic.List<LookupRelatedDataManagementServiceSR.LookupRelationContainerDetailDataRecords> DetailRecordsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LookupRelatedDataManagementServiceSR.LookupInfo MasterLookup
        {
            get
            {
                return this.MasterLookupField;
            }
            set
            {
                this.MasterLookupField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public LookupRelatedDataManagementServiceSR.LookupInfo DetailLookup
        {
            get
            {
                return this.DetailLookupField;
            }
            set
            {
                this.DetailLookupField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public LookupRelatedDataManagementServiceSR.LookupRecord MasterRecord
        {
            get
            {
                return this.MasterRecordField;
            }
            set
            {
                this.MasterRecordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.Collections.Generic.List<LookupRelatedDataManagementServiceSR.LookupRelationContainerDetailDataRecords> DetailRecords
        {
            get
            {
                return this.DetailRecordsField;
            }
            set
            {
                this.DetailRecordsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetLookupRelationalRecordParentsResponse", Namespace="http://TETCO.SOA.Entity.MDM.DataContracts.Responses/LookupRelatedData/GetLookupRe" +
        "lationalRecordParentsResponse/V1.0")]
    public partial class GetLookupRelationalRecordParentsResponse : LookupRelatedDataManagementServiceSR.ResponseBase
    {
        
        private System.Collections.Generic.List<LookupRelatedDataManagementServiceSR.LookupRelationContainerDetailDataRecords> ParentRelationalRecordsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<LookupRelatedDataManagementServiceSR.LookupRelationContainerDetailDataRecords> ParentRelationalRecords
        {
            get
            {
                return this.ParentRelationalRecordsField;
            }
            set
            {
                this.ParentRelationalRecordsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetLookupRelationalRecordsResponse", Namespace="http://TETCO.SOA.Entity.MDM.DataContracts.Responses/LookupRelatedData/GetLookupRe" +
        "lationalRecordsResponse/V1.0")]
    public partial class GetLookupRelationalRecordsResponse : LookupRelatedDataManagementServiceSR.ResponseBase
    {
        
        private LookupRelatedDataManagementServiceSR.LookupInfo MasterLookupField;
        
        private LookupRelatedDataManagementServiceSR.LookupInfo DetailLookupField;
        
        private LookupRelatedDataManagementServiceSR.LookupRecord MasterRecordField;
        
        private System.Collections.Generic.List<LookupRelatedDataManagementServiceSR.LookupRelationContainerDetailDataRecords> DetailRecordsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LookupRelatedDataManagementServiceSR.LookupInfo MasterLookup
        {
            get
            {
                return this.MasterLookupField;
            }
            set
            {
                this.MasterLookupField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public LookupRelatedDataManagementServiceSR.LookupInfo DetailLookup
        {
            get
            {
                return this.DetailLookupField;
            }
            set
            {
                this.DetailLookupField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public LookupRelatedDataManagementServiceSR.LookupRecord MasterRecord
        {
            get
            {
                return this.MasterRecordField;
            }
            set
            {
                this.MasterRecordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.Collections.Generic.List<LookupRelatedDataManagementServiceSR.LookupRelationContainerDetailDataRecords> DetailRecords
        {
            get
            {
                return this.DetailRecordsField;
            }
            set
            {
                this.DetailRecordsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LookupInfo", Namespace="http://TETCO.SOA.Entity.MDM.DataContracts/LookupInfo/V1.0")]
    public partial class LookupInfo : object
    {
        
        private string CodeField;
        
        private string Name_EnField;
        
        private string Name_ArField;
        
        private string PhysicalNameField;
        
        private string NoteField;
        
        private bool IslockedField;
        
        private bool IsActiveField;
        
        private LookupRelatedDataManagementServiceSR.Category CategoryField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code
        {
            get
            {
                return this.CodeField;
            }
            set
            {
                this.CodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name_En
        {
            get
            {
                return this.Name_EnField;
            }
            set
            {
                this.Name_EnField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string Name_Ar
        {
            get
            {
                return this.Name_ArField;
            }
            set
            {
                this.Name_ArField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string PhysicalName
        {
            get
            {
                return this.PhysicalNameField;
            }
            set
            {
                this.PhysicalNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string Note
        {
            get
            {
                return this.NoteField;
            }
            set
            {
                this.NoteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public bool Islocked
        {
            get
            {
                return this.IslockedField;
            }
            set
            {
                this.IslockedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public bool IsActive
        {
            get
            {
                return this.IsActiveField;
            }
            set
            {
                this.IsActiveField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public LookupRelatedDataManagementServiceSR.Category Category
        {
            get
            {
                return this.CategoryField;
            }
            set
            {
                this.CategoryField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LookupRecord", Namespace="http://TETCO.SOA.Entity.MDM.DataContracts/LookupRecord/V1.0")]
    public partial class LookupRecord : object
    {
        
        private string CodeField;
        
        private int BusinessCodeField;
        
        private string Name_EnField;
        
        private string Name_ArField;
        
        private string NoteField;
        
        private bool IsActiveField;
        
        private bool IslockedField;
        
        private System.Collections.Generic.List<LookupRelatedDataManagementServiceSR.Dictionary> DictionariesField;
        
        private System.Collections.Generic.List<LookupRelatedDataManagementServiceSR.LookupMetadataFieldData> LookupMetadataFieldDataField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code
        {
            get
            {
                return this.CodeField;
            }
            set
            {
                this.CodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int BusinessCode
        {
            get
            {
                return this.BusinessCodeField;
            }
            set
            {
                this.BusinessCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string Name_En
        {
            get
            {
                return this.Name_EnField;
            }
            set
            {
                this.Name_EnField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string Name_Ar
        {
            get
            {
                return this.Name_ArField;
            }
            set
            {
                this.Name_ArField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string Note
        {
            get
            {
                return this.NoteField;
            }
            set
            {
                this.NoteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public bool IsActive
        {
            get
            {
                return this.IsActiveField;
            }
            set
            {
                this.IsActiveField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public bool Islocked
        {
            get
            {
                return this.IslockedField;
            }
            set
            {
                this.IslockedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public System.Collections.Generic.List<LookupRelatedDataManagementServiceSR.Dictionary> Dictionaries
        {
            get
            {
                return this.DictionariesField;
            }
            set
            {
                this.DictionariesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public System.Collections.Generic.List<LookupRelatedDataManagementServiceSR.LookupMetadataFieldData> LookupMetadataFieldData
        {
            get
            {
                return this.LookupMetadataFieldDataField;
            }
            set
            {
                this.LookupMetadataFieldDataField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LookupRelationContainerDetailDataRecords", Namespace="http://TETCO.SOA.Entity.MDM.DataContracts/LookupRelationContainerDetailDataRecord" +
        "s/V1.0")]
    public partial class LookupRelationContainerDetailDataRecords : object
    {
        
        private string CodeField;
        
        private int BusinessCodeField;
        
        private string RelationDetailCodeField;
        
        private string RelationDetailParentCodeField;
        
        private string Name_EnField;
        
        private string Name_ArField;
        
        private string NoteField;
        
        private bool IsActiveField;
        
        private bool IslockedField;
        
        private System.Collections.Generic.List<LookupRelatedDataManagementServiceSR.Dictionary> DictionariesField;
        
        private System.Collections.Generic.List<LookupRelatedDataManagementServiceSR.LookupMetadataFieldData> LookupMetadataFieldDataField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code
        {
            get
            {
                return this.CodeField;
            }
            set
            {
                this.CodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int BusinessCode
        {
            get
            {
                return this.BusinessCodeField;
            }
            set
            {
                this.BusinessCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string RelationDetailCode
        {
            get
            {
                return this.RelationDetailCodeField;
            }
            set
            {
                this.RelationDetailCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string RelationDetailParentCode
        {
            get
            {
                return this.RelationDetailParentCodeField;
            }
            set
            {
                this.RelationDetailParentCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string Name_En
        {
            get
            {
                return this.Name_EnField;
            }
            set
            {
                this.Name_EnField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public string Name_Ar
        {
            get
            {
                return this.Name_ArField;
            }
            set
            {
                this.Name_ArField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public string Note
        {
            get
            {
                return this.NoteField;
            }
            set
            {
                this.NoteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public bool IsActive
        {
            get
            {
                return this.IsActiveField;
            }
            set
            {
                this.IsActiveField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public bool Islocked
        {
            get
            {
                return this.IslockedField;
            }
            set
            {
                this.IslockedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public System.Collections.Generic.List<LookupRelatedDataManagementServiceSR.Dictionary> Dictionaries
        {
            get
            {
                return this.DictionariesField;
            }
            set
            {
                this.DictionariesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public System.Collections.Generic.List<LookupRelatedDataManagementServiceSR.LookupMetadataFieldData> LookupMetadataFieldData
        {
            get
            {
                return this.LookupMetadataFieldDataField;
            }
            set
            {
                this.LookupMetadataFieldDataField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ESBFault", Namespace="http://TETCO.SOA.Common.DataContracts.Faults/ESBFault/V1.0")]
    public partial class ESBFault : object
    {
        
        private string MessageField;
        
        private string DetailsField;
        
        private string CodeField;
        
        private string ServiceField;
        
        private string OperationField;
        
        private LookupRelatedDataManagementServiceSR.FaultType TypeField;
        
        private LookupRelatedDataManagementServiceSR.FaultSource SourceField;
        
        private string HelpActionField;
        
        private System.DateTime OccurredAtField;
        
        private System.Collections.Generic.List<LookupRelatedDataManagementServiceSR.ActionHistory> ActionsHistoryField;
        
        private LookupRelatedDataManagementServiceSR.ESBFault InnerFaultField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public string Details
        {
            get
            {
                return this.DetailsField;
            }
            set
            {
                this.DetailsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public string Code
        {
            get
            {
                return this.CodeField;
            }
            set
            {
                this.CodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public string Service
        {
            get
            {
                return this.ServiceField;
            }
            set
            {
                this.ServiceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public string Operation
        {
            get
            {
                return this.OperationField;
            }
            set
            {
                this.OperationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public LookupRelatedDataManagementServiceSR.FaultType Type
        {
            get
            {
                return this.TypeField;
            }
            set
            {
                this.TypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public LookupRelatedDataManagementServiceSR.FaultSource Source
        {
            get
            {
                return this.SourceField;
            }
            set
            {
                this.SourceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public string HelpAction
        {
            get
            {
                return this.HelpActionField;
            }
            set
            {
                this.HelpActionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public System.DateTime OccurredAt
        {
            get
            {
                return this.OccurredAtField;
            }
            set
            {
                this.OccurredAtField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public System.Collections.Generic.List<LookupRelatedDataManagementServiceSR.ActionHistory> ActionsHistory
        {
            get
            {
                return this.ActionsHistoryField;
            }
            set
            {
                this.ActionsHistoryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public LookupRelatedDataManagementServiceSR.ESBFault InnerFault
        {
            get
            {
                return this.InnerFaultField;
            }
            set
            {
                this.InnerFaultField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Result", Namespace="http://schemas.datacontract.org/2004/07/TETCO.SOA.Common.DataContracts.Operations" +
        "Results")]
    public enum Result : byte
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Succeed = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Failed = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FaultType", Namespace="http://schemas.datacontract.org/2004/07/TETCO.SOA.Common.DataContracts.Faults")]
    public enum FaultType : byte
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unknown = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Technical = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Business = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FaultSource", Namespace="http://schemas.datacontract.org/2004/07/TETCO.SOA.Common.DataContracts.Faults")]
    public enum FaultSource : byte
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unknown = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Internal = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        External = 3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ActionHistory", Namespace="http://TETCO.SOA.Common.DataContracts.Faults/ActionHistory/V1.0")]
    public partial class ActionHistory : object
    {
        
        private string ActionField;
        
        private string ActionByField;
        
        private System.DateTime OccurredAtField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Action
        {
            get
            {
                return this.ActionField;
            }
            set
            {
                this.ActionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string ActionBy
        {
            get
            {
                return this.ActionByField;
            }
            set
            {
                this.ActionByField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime OccurredAt
        {
            get
            {
                return this.OccurredAtField;
            }
            set
            {
                this.OccurredAtField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Category", Namespace="http://TETCO.SOA.Entity.MDM.DataContracts/Category/V1.0")]
    public partial class Category : object
    {
        
        private string CodeField;
        
        private string Name_EnField;
        
        private string Name_ArField;
        
        private bool IsActiveField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code
        {
            get
            {
                return this.CodeField;
            }
            set
            {
                this.CodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name_En
        {
            get
            {
                return this.Name_EnField;
            }
            set
            {
                this.Name_EnField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string Name_Ar
        {
            get
            {
                return this.Name_ArField;
            }
            set
            {
                this.Name_ArField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public bool IsActive
        {
            get
            {
                return this.IsActiveField;
            }
            set
            {
                this.IsActiveField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Dictionary", Namespace="http://TETCO.SOA.Entity.MDM.DataContracts/Dictionary/V1.0")]
    public partial class Dictionary : object
    {
        
        private string CodeField;
        
        private LookupRelatedDataManagementServiceSR.Language LanguageField;
        
        private string TranslationValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code
        {
            get
            {
                return this.CodeField;
            }
            set
            {
                this.CodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LookupRelatedDataManagementServiceSR.Language Language
        {
            get
            {
                return this.LanguageField;
            }
            set
            {
                this.LanguageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TranslationValue
        {
            get
            {
                return this.TranslationValueField;
            }
            set
            {
                this.TranslationValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LookupMetadataFieldData", Namespace="http://TETCO.SOA.Entity.MDM.DataContracts/LookupMetadataFieldData/V1.0")]
    public partial class LookupMetadataFieldData : object
    {
        
        private string CodeField;
        
        private LookupRelatedDataManagementServiceSR.MetadataField MetadataFieldField;
        
        private string FieldValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code
        {
            get
            {
                return this.CodeField;
            }
            set
            {
                this.CodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LookupRelatedDataManagementServiceSR.MetadataField MetadataField
        {
            get
            {
                return this.MetadataFieldField;
            }
            set
            {
                this.MetadataFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string FieldValue
        {
            get
            {
                return this.FieldValueField;
            }
            set
            {
                this.FieldValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Language", Namespace="http://TETCO.SOA.Entity.MDM.DataContracts/Language/V1.0")]
    public partial class Language : object
    {
        
        private string CodeField;
        
        private string Name_EnField;
        
        private string Name_ArField;
        
        private bool IsActiveField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code
        {
            get
            {
                return this.CodeField;
            }
            set
            {
                this.CodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name_En
        {
            get
            {
                return this.Name_EnField;
            }
            set
            {
                this.Name_EnField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string Name_Ar
        {
            get
            {
                return this.Name_ArField;
            }
            set
            {
                this.Name_ArField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public bool IsActive
        {
            get
            {
                return this.IsActiveField;
            }
            set
            {
                this.IsActiveField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MetadataField", Namespace="http://TETCO.SOA.Entity.MDM.DataContracts/MetadataField/V1.0")]
    public partial class MetadataField : object
    {
        
        private string CodeField;
        
        private string Name_EnField;
        
        private string Name_ArField;
        
        private int FieldTypeField;
        
        private bool IsActiveField;
        
        private string RegexField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code
        {
            get
            {
                return this.CodeField;
            }
            set
            {
                this.CodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name_En
        {
            get
            {
                return this.Name_EnField;
            }
            set
            {
                this.Name_EnField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string Name_Ar
        {
            get
            {
                return this.Name_ArField;
            }
            set
            {
                this.Name_ArField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int FieldType
        {
            get
            {
                return this.FieldTypeField;
            }
            set
            {
                this.FieldTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public bool IsActive
        {
            get
            {
                return this.IsActiveField;
            }
            set
            {
                this.IsActiveField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public string Regex
        {
            get
            {
                return this.RegexField;
            }
            set
            {
                this.RegexField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetLookupRelationalRecordParentsRequest", Namespace="http://TETCO.SOA.Entity.MDM.DataContracts.Requests/LookupRelatedData/GetLookupRel" +
        "ationalRecordParentsRequest/V1.0")]
    public partial class GetLookupRelationalRecordParentsRequest : object
    {
        
        private string RelationContainerCodeField;
        
        private string DetailLookupCodeField;
        
        private int DetailRecordBusinessCodeField;
        
        private string ParentCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RelationContainerCode
        {
            get
            {
                return this.RelationContainerCodeField;
            }
            set
            {
                this.RelationContainerCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string DetailLookupCode
        {
            get
            {
                return this.DetailLookupCodeField;
            }
            set
            {
                this.DetailLookupCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int DetailRecordBusinessCode
        {
            get
            {
                return this.DetailRecordBusinessCodeField;
            }
            set
            {
                this.DetailRecordBusinessCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string ParentCode
        {
            get
            {
                return this.ParentCodeField;
            }
            set
            {
                this.ParentCodeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetLookupRelationalRecordsByLookupNameAndBusinessCodeRequest", Namespace="http://TETCO.SOA.Entity.MDM.DataContracts.Requests/LookupRelatedData/GetLookupRel" +
        "ationalRecordsByLookupNameAndBusinessCodeRequest/V1.0")]
    public partial class GetLookupRelationalRecordsByLookupNameAndBusinessCodeRequest : object
    {
        
        private string RelationContainerCodeField;
        
        private string MasterLookupNameField;
        
        private int MasterRecordBusinessCodeField;
        
        private System.Collections.Generic.List<string> LanguageCodesField;
        
        private System.Collections.Generic.List<string> MetadataFieldCodesField;
        
        private string ParentCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RelationContainerCode
        {
            get
            {
                return this.RelationContainerCodeField;
            }
            set
            {
                this.RelationContainerCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string MasterLookupName
        {
            get
            {
                return this.MasterLookupNameField;
            }
            set
            {
                this.MasterLookupNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int MasterRecordBusinessCode
        {
            get
            {
                return this.MasterRecordBusinessCodeField;
            }
            set
            {
                this.MasterRecordBusinessCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.Collections.Generic.List<string> LanguageCodes
        {
            get
            {
                return this.LanguageCodesField;
            }
            set
            {
                this.LanguageCodesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public System.Collections.Generic.List<string> MetadataFieldCodes
        {
            get
            {
                return this.MetadataFieldCodesField;
            }
            set
            {
                this.MetadataFieldCodesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public string ParentCode
        {
            get
            {
                return this.ParentCodeField;
            }
            set
            {
                this.ParentCodeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetLookupRelationalRecordsByBusinessCodeRequest", Namespace="http://TETCO.SOA.Entity.MDM.DataContracts.Requests/LookupRelatedData/GetLookupRel" +
        "ationalRecordsByBusinessCodeRequest/V1.0")]
    public partial class GetLookupRelationalRecordsByBusinessCodeRequest : object
    {
        
        private string RelationContainerCodeField;
        
        private string MasterLookupCodeField;
        
        private int MasterRecordBusinessCodeField;
        
        private System.Collections.Generic.List<string> LanguageCodesField;
        
        private System.Collections.Generic.List<string> MetadataFieldCodesField;
        
        private string ParentCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RelationContainerCode
        {
            get
            {
                return this.RelationContainerCodeField;
            }
            set
            {
                this.RelationContainerCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string MasterLookupCode
        {
            get
            {
                return this.MasterLookupCodeField;
            }
            set
            {
                this.MasterLookupCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int MasterRecordBusinessCode
        {
            get
            {
                return this.MasterRecordBusinessCodeField;
            }
            set
            {
                this.MasterRecordBusinessCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.Collections.Generic.List<string> LanguageCodes
        {
            get
            {
                return this.LanguageCodesField;
            }
            set
            {
                this.LanguageCodesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public System.Collections.Generic.List<string> MetadataFieldCodes
        {
            get
            {
                return this.MetadataFieldCodesField;
            }
            set
            {
                this.MetadataFieldCodesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public string ParentCode
        {
            get
            {
                return this.ParentCodeField;
            }
            set
            {
                this.ParentCodeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetLookupRelationalRecordsByBusinessCodeNoParentCodeRequest", Namespace="http://TETCO.SOA.Entity.MDM.DataContracts.Requests/LookupRelatedData/GetLookupRel" +
        "ationalRecordsByBusinessCodeNoParentCodeRequest/V1.0")]
    public partial class GetLookupRelationalRecordsByBusinessCodeNoParentCodeRequest : object
    {
        
        private string RelationContainerCodeField;
        
        private string MasterLookupCodeField;
        
        private int MasterRecordBusinessCodeField;
        
        private System.Collections.Generic.List<string> LanguageCodesField;
        
        private System.Collections.Generic.List<string> MetadataFieldCodesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RelationContainerCode
        {
            get
            {
                return this.RelationContainerCodeField;
            }
            set
            {
                this.RelationContainerCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string MasterLookupCode
        {
            get
            {
                return this.MasterLookupCodeField;
            }
            set
            {
                this.MasterLookupCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int MasterRecordBusinessCode
        {
            get
            {
                return this.MasterRecordBusinessCodeField;
            }
            set
            {
                this.MasterRecordBusinessCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.Collections.Generic.List<string> LanguageCodes
        {
            get
            {
                return this.LanguageCodesField;
            }
            set
            {
                this.LanguageCodesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public System.Collections.Generic.List<string> MetadataFieldCodes
        {
            get
            {
                return this.MetadataFieldCodesField;
            }
            set
            {
                this.MetadataFieldCodesField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetLookupRelationalRecordsByMetadataRequest", Namespace="http://TETCO.SOA.Entity.MDM.DataContracts.Requests/LookupRelatedData/GetLookupRel" +
        "ationalRecordsByMetadataRequest/V1.0")]
    public partial class GetLookupRelationalRecordsByMetadataRequest : object
    {
        
        private string RelationContainerCodeField;
        
        private string MasterLookupCodeField;
        
        private System.Collections.Generic.List<LookupRelatedDataManagementServiceSR.LookupMetadataFieldData> MetadataFieldValuesField;
        
        private System.Collections.Generic.List<string> LanguageCodesField;
        
        private System.Collections.Generic.List<string> MetadataFieldCodesField;
        
        private string ParentCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RelationContainerCode
        {
            get
            {
                return this.RelationContainerCodeField;
            }
            set
            {
                this.RelationContainerCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string MasterLookupCode
        {
            get
            {
                return this.MasterLookupCodeField;
            }
            set
            {
                this.MasterLookupCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.Collections.Generic.List<LookupRelatedDataManagementServiceSR.LookupMetadataFieldData> MetadataFieldValues
        {
            get
            {
                return this.MetadataFieldValuesField;
            }
            set
            {
                this.MetadataFieldValuesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.Collections.Generic.List<string> LanguageCodes
        {
            get
            {
                return this.LanguageCodesField;
            }
            set
            {
                this.LanguageCodesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public System.Collections.Generic.List<string> MetadataFieldCodes
        {
            get
            {
                return this.MetadataFieldCodesField;
            }
            set
            {
                this.MetadataFieldCodesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public string ParentCode
        {
            get
            {
                return this.ParentCodeField;
            }
            set
            {
                this.ParentCodeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AttachLookupRecordsRequest", Namespace="http://TETCO.SOA.Entity.MDM.DataContracts.Requests/LookupRelatedData/AttachLookup" +
        "RecordsRequest/V1.0")]
    public partial class AttachLookupRecordsRequest : object
    {
        
        private string RelationContainerCodeField;
        
        private string MasterLookupCodeField;
        
        private string DetailLookupCodeField;
        
        private string MasterRecordCodeField;
        
        private string DetailRecordCodeField;
        
        private string ParentCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RelationContainerCode
        {
            get
            {
                return this.RelationContainerCodeField;
            }
            set
            {
                this.RelationContainerCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string MasterLookupCode
        {
            get
            {
                return this.MasterLookupCodeField;
            }
            set
            {
                this.MasterLookupCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string DetailLookupCode
        {
            get
            {
                return this.DetailLookupCodeField;
            }
            set
            {
                this.DetailLookupCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string MasterRecordCode
        {
            get
            {
                return this.MasterRecordCodeField;
            }
            set
            {
                this.MasterRecordCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string DetailRecordCode
        {
            get
            {
                return this.DetailRecordCodeField;
            }
            set
            {
                this.DetailRecordCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public string ParentCode
        {
            get
            {
                return this.ParentCodeField;
            }
            set
            {
                this.ParentCodeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DetachLookupRecordsRequest", Namespace="http://TETCO.SOA.Entity.MDM.DataContracts.Requests/LookupRelatedData/DetachLookup" +
        "RecordsRequest/V1.0")]
    public partial class DetachLookupRecordsRequest : object
    {
        
        private string CodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code
        {
            get
            {
                return this.CodeField;
            }
            set
            {
                this.CodeField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://TETCO.SOA.Entity.MDM.ServiceContracts/ILookupRelatedDataManagementService/" +
        "V1.0", ConfigurationName="LookupRelatedDataManagementServiceSR.ILookupRelatedDataManagementService")]
    public interface ILookupRelatedDataManagementService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://TETCO.SOA.Entity.MDM.ServiceContracts/ILookupRelatedDataManagementService/" +
            "V1.0/ILookupRelatedDataManagementService/GetLookupRelationalRecords", ReplyAction="http://TETCO.SOA.Entity.MDM.ServiceContracts/ILookupRelatedDataManagementService/" +
            "V1.0/ILookupRelatedDataManagementService/GetLookupRelationalRecordsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(LookupRelatedDataManagementServiceSR.ESBFault), Action="http://TETCO.SOA.Entity.MDM.ServiceContracts/ILookupRelatedDataManagementService/" +
            "V1.0/ILookupRelatedDataManagementService/GetLookupRelationalRecordsESBFault_V_1_" +
            "0Fault", Name="ESBFault", Namespace="http://TETCO.SOA.Common.DataContracts.Faults/ESBFault/V1.0")]
        System.Threading.Tasks.Task<LookupRelatedDataManagementServiceSR.GetLookupRelationalRecordsResponse> GetLookupRelationalRecordsAsync(LookupRelatedDataManagementServiceSR.GetLookupRelationalRecordsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://TETCO.SOA.Entity.MDM.ServiceContracts/ILookupRelatedDataManagementService/" +
            "V1.0/ILookupRelatedDataManagementService/GetLookupRelationalRecordParents", ReplyAction="http://TETCO.SOA.Entity.MDM.ServiceContracts/ILookupRelatedDataManagementService/" +
            "V1.0/ILookupRelatedDataManagementService/GetLookupRelationalRecordParentsRespons" +
            "e")]
        [System.ServiceModel.FaultContractAttribute(typeof(LookupRelatedDataManagementServiceSR.ESBFault), Action="http://TETCO.SOA.Entity.MDM.ServiceContracts/ILookupRelatedDataManagementService/" +
            "V1.0/ILookupRelatedDataManagementService/GetLookupRelationalRecordParentsESBFaul" +
            "t_V_1_0Fault", Name="ESBFault", Namespace="http://TETCO.SOA.Common.DataContracts.Faults/ESBFault/V1.0")]
        System.Threading.Tasks.Task<LookupRelatedDataManagementServiceSR.GetLookupRelationalRecordParentsResponse> GetLookupRelationalRecordParentsAsync(LookupRelatedDataManagementServiceSR.GetLookupRelationalRecordParentsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://TETCO.SOA.Entity.MDM.ServiceContracts/ILookupRelatedDataManagementService/" +
            "V1.0/ILookupRelatedDataManagementService/GetLookupRelationalRecordsByLookupNameA" +
            "ndBusinessCode", ReplyAction="http://TETCO.SOA.Entity.MDM.ServiceContracts/ILookupRelatedDataManagementService/" +
            "V1.0/ILookupRelatedDataManagementService/GetLookupRelationalRecordsByLookupNameA" +
            "ndBusinessCodeResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(LookupRelatedDataManagementServiceSR.ESBFault), Action="http://TETCO.SOA.Entity.MDM.ServiceContracts/ILookupRelatedDataManagementService/" +
            "V1.0/ILookupRelatedDataManagementService/GetLookupRelationalRecordsByLookupNameA" +
            "ndBusinessCodeESBFault_V_1_0Fault", Name="ESBFault", Namespace="http://TETCO.SOA.Common.DataContracts.Faults/ESBFault/V1.0")]
        System.Threading.Tasks.Task<LookupRelatedDataManagementServiceSR.GetLookupRelationalRecordsByLookupNameAndBusinessCodeResponse> GetLookupRelationalRecordsByLookupNameAndBusinessCodeAsync(LookupRelatedDataManagementServiceSR.GetLookupRelationalRecordsByLookupNameAndBusinessCodeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://TETCO.SOA.Entity.MDM.ServiceContracts/ILookupRelatedDataManagementService/" +
            "V1.0/ILookupRelatedDataManagementService/GetLookupRelationalRecordsByBusinessCod" +
            "e", ReplyAction="http://TETCO.SOA.Entity.MDM.ServiceContracts/ILookupRelatedDataManagementService/" +
            "V1.0/ILookupRelatedDataManagementService/GetLookupRelationalRecordsByBusinessCod" +
            "eResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(LookupRelatedDataManagementServiceSR.ESBFault), Action="http://TETCO.SOA.Entity.MDM.ServiceContracts/ILookupRelatedDataManagementService/" +
            "V1.0/ILookupRelatedDataManagementService/GetLookupRelationalRecordsByBusinessCod" +
            "eESBFault_V_1_0Fault", Name="ESBFault", Namespace="http://TETCO.SOA.Common.DataContracts.Faults/ESBFault/V1.0")]
        System.Threading.Tasks.Task<LookupRelatedDataManagementServiceSR.GetLookupRelationalRecordsByBusinessCodeResponse> GetLookupRelationalRecordsByBusinessCodeAsync(LookupRelatedDataManagementServiceSR.GetLookupRelationalRecordsByBusinessCodeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://TETCO.SOA.Entity.MDM.ServiceContracts/ILookupRelatedDataManagementService/" +
            "V1.0/ILookupRelatedDataManagementService/GetLookupRelationalRecordsByBusinessCod" +
            "eNoParentCode", ReplyAction="http://TETCO.SOA.Entity.MDM.ServiceContracts/ILookupRelatedDataManagementService/" +
            "V1.0/ILookupRelatedDataManagementService/GetLookupRelationalRecordsByBusinessCod" +
            "eNoParentCodeResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(LookupRelatedDataManagementServiceSR.ESBFault), Action="http://TETCO.SOA.Entity.MDM.ServiceContracts/ILookupRelatedDataManagementService/" +
            "V1.0/ILookupRelatedDataManagementService/GetLookupRelationalRecordsByBusinessCod" +
            "eNoParentCodeESBFault_V_1_0Fault", Name="ESBFault", Namespace="http://TETCO.SOA.Common.DataContracts.Faults/ESBFault/V1.0")]
        System.Threading.Tasks.Task<LookupRelatedDataManagementServiceSR.GetLookupRelationalRecordsByBusinessCodeNoParentCodeResponse> GetLookupRelationalRecordsByBusinessCodeNoParentCodeAsync(LookupRelatedDataManagementServiceSR.GetLookupRelationalRecordsByBusinessCodeNoParentCodeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://TETCO.SOA.Entity.MDM.ServiceContracts/ILookupRelatedDataManagementService/" +
            "V1.0/ILookupRelatedDataManagementService/GetLookupRelationalRecordsByMetadata", ReplyAction="http://TETCO.SOA.Entity.MDM.ServiceContracts/ILookupRelatedDataManagementService/" +
            "V1.0/ILookupRelatedDataManagementService/GetLookupRelationalRecordsByMetadataRes" +
            "ponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(LookupRelatedDataManagementServiceSR.ESBFault), Action="http://TETCO.SOA.Entity.MDM.ServiceContracts/ILookupRelatedDataManagementService/" +
            "V1.0/ILookupRelatedDataManagementService/GetLookupRelationalRecordsByMetadataESB" +
            "Fault_V_1_0Fault", Name="ESBFault", Namespace="http://TETCO.SOA.Common.DataContracts.Faults/ESBFault/V1.0")]
        System.Threading.Tasks.Task<LookupRelatedDataManagementServiceSR.GetLookupRelationalRecordsByMetadataResponse> GetLookupRelationalRecordsByMetadataAsync(LookupRelatedDataManagementServiceSR.GetLookupRelationalRecordsByMetadataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://TETCO.SOA.Entity.MDM.ServiceContracts/ILookupRelatedDataManagementService/" +
            "V1.0/ILookupRelatedDataManagementService/AttachLookupRecords", ReplyAction="http://TETCO.SOA.Entity.MDM.ServiceContracts/ILookupRelatedDataManagementService/" +
            "V1.0/ILookupRelatedDataManagementService/AttachLookupRecordsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(LookupRelatedDataManagementServiceSR.ESBFault), Action="http://TETCO.SOA.Entity.MDM.ServiceContracts/ILookupRelatedDataManagementService/" +
            "V1.0/ILookupRelatedDataManagementService/AttachLookupRecordsESBFault_V_1_0Fault", Name="ESBFault", Namespace="http://TETCO.SOA.Common.DataContracts.Faults/ESBFault/V1.0")]
        System.Threading.Tasks.Task<LookupRelatedDataManagementServiceSR.AttachLookupRecordsResponse> AttachLookupRecordsAsync(LookupRelatedDataManagementServiceSR.AttachLookupRecordsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://TETCO.SOA.Entity.MDM.ServiceContracts/ILookupRelatedDataManagementService/" +
            "V1.0/ILookupRelatedDataManagementService/DetachLookupRecords", ReplyAction="http://TETCO.SOA.Entity.MDM.ServiceContracts/ILookupRelatedDataManagementService/" +
            "V1.0/ILookupRelatedDataManagementService/DetachLookupRecordsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(LookupRelatedDataManagementServiceSR.ESBFault), Action="http://TETCO.SOA.Entity.MDM.ServiceContracts/ILookupRelatedDataManagementService/" +
            "V1.0/ILookupRelatedDataManagementService/DetachLookupRecordsESBFault_V_1_0Fault", Name="ESBFault", Namespace="http://TETCO.SOA.Common.DataContracts.Faults/ESBFault/V1.0")]
        System.Threading.Tasks.Task<LookupRelatedDataManagementServiceSR.DetachLookupRecordsResponse> DetachLookupRecordsAsync(LookupRelatedDataManagementServiceSR.DetachLookupRecordsRequest request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface ILookupRelatedDataManagementServiceChannel : LookupRelatedDataManagementServiceSR.ILookupRelatedDataManagementService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class LookupRelatedDataManagementServiceClient : System.ServiceModel.ClientBase<LookupRelatedDataManagementServiceSR.ILookupRelatedDataManagementService>, LookupRelatedDataManagementServiceSR.ILookupRelatedDataManagementService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public LookupRelatedDataManagementServiceClient() : 
                base(LookupRelatedDataManagementServiceClient.GetDefaultBinding(), LookupRelatedDataManagementServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.ESBDefaultEndpoint.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public LookupRelatedDataManagementServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(LookupRelatedDataManagementServiceClient.GetBindingForEndpoint(endpointConfiguration), LookupRelatedDataManagementServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public LookupRelatedDataManagementServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(LookupRelatedDataManagementServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public LookupRelatedDataManagementServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(LookupRelatedDataManagementServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public LookupRelatedDataManagementServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<LookupRelatedDataManagementServiceSR.GetLookupRelationalRecordsResponse> GetLookupRelationalRecordsAsync(LookupRelatedDataManagementServiceSR.GetLookupRelationalRecordsRequest request)
        {
            return base.Channel.GetLookupRelationalRecordsAsync(request);
        }
        
        public System.Threading.Tasks.Task<LookupRelatedDataManagementServiceSR.GetLookupRelationalRecordParentsResponse> GetLookupRelationalRecordParentsAsync(LookupRelatedDataManagementServiceSR.GetLookupRelationalRecordParentsRequest request)
        {
            return base.Channel.GetLookupRelationalRecordParentsAsync(request);
        }
        
        public System.Threading.Tasks.Task<LookupRelatedDataManagementServiceSR.GetLookupRelationalRecordsByLookupNameAndBusinessCodeResponse> GetLookupRelationalRecordsByLookupNameAndBusinessCodeAsync(LookupRelatedDataManagementServiceSR.GetLookupRelationalRecordsByLookupNameAndBusinessCodeRequest request)
        {
            return base.Channel.GetLookupRelationalRecordsByLookupNameAndBusinessCodeAsync(request);
        }
        
        public System.Threading.Tasks.Task<LookupRelatedDataManagementServiceSR.GetLookupRelationalRecordsByBusinessCodeResponse> GetLookupRelationalRecordsByBusinessCodeAsync(LookupRelatedDataManagementServiceSR.GetLookupRelationalRecordsByBusinessCodeRequest request)
        {
            return base.Channel.GetLookupRelationalRecordsByBusinessCodeAsync(request);
        }
        
        public System.Threading.Tasks.Task<LookupRelatedDataManagementServiceSR.GetLookupRelationalRecordsByBusinessCodeNoParentCodeResponse> GetLookupRelationalRecordsByBusinessCodeNoParentCodeAsync(LookupRelatedDataManagementServiceSR.GetLookupRelationalRecordsByBusinessCodeNoParentCodeRequest request)
        {
            return base.Channel.GetLookupRelationalRecordsByBusinessCodeNoParentCodeAsync(request);
        }
        
        public System.Threading.Tasks.Task<LookupRelatedDataManagementServiceSR.GetLookupRelationalRecordsByMetadataResponse> GetLookupRelationalRecordsByMetadataAsync(LookupRelatedDataManagementServiceSR.GetLookupRelationalRecordsByMetadataRequest request)
        {
            return base.Channel.GetLookupRelationalRecordsByMetadataAsync(request);
        }
        
        public System.Threading.Tasks.Task<LookupRelatedDataManagementServiceSR.AttachLookupRecordsResponse> AttachLookupRecordsAsync(LookupRelatedDataManagementServiceSR.AttachLookupRecordsRequest request)
        {
            return base.Channel.AttachLookupRecordsAsync(request);
        }
        
        public System.Threading.Tasks.Task<LookupRelatedDataManagementServiceSR.DetachLookupRecordsResponse> DetachLookupRecordsAsync(LookupRelatedDataManagementServiceSR.DetachLookupRecordsRequest request)
        {
            return base.Channel.DetachLookupRecordsAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ESBDefaultEndpoint))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ESBDefaultEndpoint))
            {
                return new System.ServiceModel.EndpointAddress("http://esbstg.moe.gov.sa/Entity/MDM/LookupRelatedDataManagementService_V_1_0.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return LookupRelatedDataManagementServiceClient.GetBindingForEndpoint(EndpointConfiguration.ESBDefaultEndpoint);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return LookupRelatedDataManagementServiceClient.GetEndpointAddress(EndpointConfiguration.ESBDefaultEndpoint);
        }
        
        public enum EndpointConfiguration
        {
            
            ESBDefaultEndpoint,
        }
    }
}
